language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO_VERSION=1.4.11
  - DJANGO_VERSION=1.5.5
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7

matrix:
  exclude:
    # Python 2.6 support has been dropped in Django 1.7
    - python: "2.6"
      env: DJANGO_VERSION=1.7

install:
  - pip install Django==$DJANGO_VERSION
  - pip install -r requirements-test.txt

script: coverage run --source rest_framework_proxy runtests.py

after_success: coveralls
