language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q -r requirements-test.txt

script: coverage run --source rest_framework_proxy runtests.py

after_success: coveralls
