language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

sudo: false

env:
  - Django=1.8
  - Django=1.9
  - Django=1.10
  - Django=1.11

matrix:
  fast_finish: true
  include:
    # Django 1.11 is the first version to officially support Python 3.6
    - python: "3.6"
      env: DJANGO=1.11
    - python: "3.3"
      env: DJANGO=1.8

install:
  - pip install tox tox-travis

script:
  - tox

after_success:
  - pip install codecov
  - codecov -e TOX_ENV;DJANGO
